theme: jekyll-theme-minimal
title: Dota 2 Sage
description: Just a small blog where I will share my research on the low-level details of Dota 2.
url: https://www.d2sage.com
permalink: /blog/:year/:month/:title.html
relative_permalinks: false
tagline: Tips and Tricks for Dota 2
